import React from 'react'
import Search from './Search';
function AnimeTitles() {
    const animeTitles = [
        'Naruto',
      'One Piece',
      'Dragon Ball',
      'Attack on Titan',
      'My Hero Academia',
      'Death Note',
      'Fullmetal Alchemist: Brotherhood',
      'Demon Slayer',
      'One Punch Man',
      'Tokyo Ghoul',
      'Hunter x Hunter',
      'Sword Art Online',
      'Cowboy Bebop',
      'Steins;Gate',
      'JoJo\'s Bizarre Adventure',
      'Neon Genesis Evangelion',
      'Bleach',
      'Fairy Tail',
      'Haikyuu!!',
      'Code Geass',
      'Your Lie in April',
      'The Promised Neverland',
      'Black Clover',
      'Assassination Classroom',
      'Mob Psycho 100',
      'Parasyte -the maxim-',
      'Death Parade',
      'Cowboy Bebop',
      'Overlord',
      'Noragami',
      'Magi: The Labyrinth of Magic',
      'Re:Zero - Starting Life in Another World',
      'Fire Force',
      'Vinland Saga',
      'Dragon Ball Z',
      'My Youth Romantic Comedy Is Wrong, As I Expected',
      'Demon Lord, Retry!',
      'Golden Time',
      'Blue Exorcist',
      'Black Lagoon',
      'Gurren Lagann',
      'Clannad',
      'K-On!',
      'Toradora!',
      'Fruits Basket',
      'Akame ga Kill!',
      'No Game No Life',
      'Psycho-Pass',
      'Serial Experiments Lain',
      'Hellsing Ultimate',
      'Trigun',
      'Great Teacher Onizuka',
      'Elfen Lied',
      'The Seven Deadly Sins',
      'High School DxD',
      'Soul Eater',
      'Danganronpa: The Animation',
      'Angel Beats!',
      'Rurouni Kenshin',
      'Baccano!',
      'Durarara!!',
      'Magical Girl Madoka Magica',
      'Cowboy Bebop',
      'Kill la Kill',
      'Noragami',
      'The Rising of the Shield Hero',
      'Black Bullet',
      'Log Horizon',
      'A Silent Voice',
      'Erased',
      'Anohana: The Flower We Saw That Day',
      'Kuroko no Basket',
      'The Devil Is a Part-Timer!',
      'Sword Art Online: Alicization',
      'Assassins Pride',
      'Tokyo Ravens',
      'Sakurasou no Pet na Kanojo',
      'Kimi no Na wa (Your Name)',
      ];
  return (
    <div>
      <h1>Anime Search</h1>
      <Search titles={animeTitles} />
    </div>
  )
}

export default AnimeTitles
